/**************************************************************
**
**   This file contains code that your project will use
**
**   DO NOT EDIT THIS file
**
**************************************************************/



#pragma once


#include <iostream>
#include <stdexcept>
#include <cstdlib>
#include <cstring>

using namespace std;

// Simulates a low-level system call to load binary data
void* loadAudioResource(int duration, string title) {

    // Testing a failure case 
    if (duration == 391 || duration == 1800) { 
        throw runtime_error("FATAL ERROR: Memory allocation failed!");
    }

    // Ensure the buffer is large enough
    int neededSize = title.length() + 1; // +1 for null terminator

    char* buffer = new char[neededSize];

    strcpy(buffer, title.c_str());

    return buffer;
    
}

void playAudioResource(void *buffer) {
    char* cstr = static_cast<char*>(buffer);

    cout << "\tPlaying - " << cstr << endl;    
}

void freeAudioResource(void *buffer) {

    cout << "  [RAII Cleanup]: freeing audio buffer memory...\n";
    char* cstr = static_cast<char*>(buffer);

    delete[] cstr;    
}