/**************************************************************
**
**   This file contains code that your project will use
**
**   DO NOT EDIT THIS file
**
**************************************************************/



#pragma once


#include <iostream>
#include <stdexcept>
#include <cstdlib>
#include <cstring>

using namespace std;

// Simulates a low-level system call to load binary data
void* loadAudioResource(int duration, string title);

// Simulates playing an audio stream.  The buffer parameter 
// represents a sound file 
void playAudioResource(void *buffer);

// You must free the buffer once you are done using it.
void freeAudioResource(void *buffer);