/**************************************************************
**
**   This file contains code that your project will use
**
**   DO NOT EDIT THIS file
**
**************************************************************/
#pragma once


#include <iostream>
#include <stdexcept>
#include <cstdlib>
#include <cstring>

using namespace std;

// Simulates a low-level system call to load binary data
void* loadAudioResource(int duration, string title);
void playAudioResource(void *buffer);
void freeAudioResource(void *buffer);